### ISSUE TITLE
Nuget dependency issue

### ISSUE THREAD

**Issue by drpeck** [umco/umbraco-content-list#6]
Thought I should check that the nuget package is correct, with the set dependency:
Our.Umbraco.InnerContent (>= 1.1.1 && < 2.0.0)

I can't install this because I have a greater InnerContent version.

**Comment by leekelleher** [comment]
@drpeck Thanks for reporting this. It's most definitely a bug. I'll get a patch release out later today.

**Comment by drpeck** [comment]
Awesome. I thought I might be being a pain in the arse. Thanks for creating this.

**Comment by leekelleher** [comment]
...and v1.0.1 is now available on NuGet: <https://www.nuget.org/packages/Our.Umbraco.ContentList/1.0.1>
